---
abstract: 'Mess around with BEGIN/CHECK/INIT/END blocks'
author:
  - 'Adriano Ferreira <ferreira@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Hook
no_index:
  directory:
    - t
    - inc
recommends:
  Test::Pod: 1.18
  Test::Pod::Coverage: 1.04
requires:
  Test::More: 0
  XSLoader: 0
  strict: 0
  warnings: 0
resources:
  repository: http://github.com/aferreira/cpan-WWW-CPAN
version: 0.006
